Repository open-component-model/delivery-service, pull requests merged in 2024-06, with the labels that each got.

#63 Check if scan exists based on artefact scan info
  compliance_summary/__init__.py
  components.py
  issue_replicator/__main__.py
Labels: needs/ok-to-test

#74 Make use of `ArtefactKind` enum
  artefact_enumerator.py
  issue_replicator/__main__.py
  k8s/backlog.py
  metadata.py
  rescore.py
  rescoring_util.py
  service_extensions.py
Labels: needs/ok-to-test

#80 Support issue-replication for `finding/malware`
  issue_replicator/__main__.py
  issue_replicator/github.py
Labels: needs/ok-to-test, area/ipcei

#59 Remove deprecated `cnudie` routes
  app.py
Labels: needs/ok-to-test, blocked/do-not-merge
