Repository open-component-model/delivery-service, pull requests merged in 2025-01, with the labels that each got.

#308 Only use sprints from compliance snapshots for issue replication
  issue_replicator/__main__.py
  issue_replicator/github.py
Labels: needs/ok-to-test

#315 Resolve depedency towards `model.base` package
  bdba/assessments.py
  bdba/client.py
  bdba/model.py
  bdba/rescore.py
  bdba/scanning.py
  bdba/util.py
  cli/_bdba.py
Labels: needs/ok-to-test

#322 Remove misleading `0 targets` in diki issues template
  issue_replicator/github.py
Labels: needs/ok-to-test

#270 Sast rescoring update
  app.py
  cm06/scan.py
  config.py
  features/__init__.py
  rescore/model.py
  rescore/utility.py
  test/test_rescoring.py
Labels: needs/ok-to-test

#324 Rename modul and include cm06 in packages
  sast.py
  setup.extensions.py
Labels: needs/ok-to-test

#325 move function to util
  components.py
  dora.py
  sast.py
  util.py
Labels: needs/ok-to-test

#326 move versionfilter to config
  cache_manager.py
  components.py
  config.py
  features/__init__.py
  sast.py
Labels: reviewed/ok-to-test

#323 Add refactored scan cfg and new finding-specific model classes
  odg/__init__.py
  odg/defaults.yaml
  odg/findings.py
  odg/scan_cfg.py
  setup.utils.py
Labels: reviewed/ok-to-test, needs/ok-to-test

#328 introduce helm chart template for sast
  charts/extensions/charts/backlog-controller/templates/sast.yaml
Labels: needs/ok-to-test

#321 Stop re-applying existing BDBA triages to new BDBA apps
  bdba/__main__.py
  bdba/assessments.py
  bdba/scanning.py
  bdba/util.py
  charts/extensions/crds/scan-configuration.yaml
  cli/_bdba.py
  config.py
  local-setup/kind/cluster/values-extensions.yaml
Labels: needs/ok-to-test, reviewed/do-not-merged
