Repository open-component-model/delivery-service, pull requests merged in 2025-02, with the labels that each got.

#341 Add logging and object validation
  sast.py
Labels: needs/ok-to-test

#335 Use refactored scan-cfg and findings-cfg for issue replicator
  issue_replicator/__main__.py
  issue_replicator/github.py
Labels: reviewed/ok-to-test, needs/ok-to-test

#343 Also filter supported artefact types for ClamAV extension
  malware/__main__.py
  odg/scan_cfg.py
Labels: reviewed/ok-to-test, needs/ok-to-test

#344 Allow skipping of vulnerability findings via skip-scan label
  bdba/model.py
  bdba/scanning.py
Labels: needs/ok-to-test

#352 Introduce `enabled` flag to extension cfgs
  odg/scan_cfg.py
  test/test_extension_cfg.py
Labels: needs/ok-to-test

#357 Fix: Close issues which "fell out" of the configured time range
  issue_replicator/__main__.py
  odg/extensions_cfg.py
Labels: needs/ok-to-test

#367 Prevent naming conflicts by renaming sast values
  artefact_enumerator.py
  charts/extensions/charts/sast/templates/sast.yaml
  issue_replicator/__main__.py
  k8s/backlog.py
  odg/extensions_cfg.py
  sast.py
  swagger/swagger.yaml
  test/test_rescoring.py
Labels: needs/ok-to-test

#370 Make SAST Logging persistent
  sast.py
Labels: reviewed/ok-to-test
